In [85]:
import requests
from bs4 import BeautifulSoup
import os
import re

def clean_folder_name(folder_name):
    # Usuń znaki specjalne i niedozwolone znaki z nazwy folderu
    return re.sub(r'[\/:*?"<>|]', '', folder_name)

download_directory = r"C:\Users\48516\Desktop\inzynierka\aktualne\klimat"
base_url = "https://danepubliczne.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/dobowe/klimat/"

for year in range(2014, 2024):
    year_url = f"{base_url}{year}/"
    
    response = requests.get(year_url)
    
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        
        for link in soup.find_all("a"):
            folder_name = link.get("href")
            
            if not folder_name or folder_name.startswith("../"):
                continue
            
            folder_url = f"{year_url}{folder_name}"
            response = requests.get(folder_url)
            
            if response.status_code == 200:
                folder_name_cleaned = clean_folder_name(folder_name)
                full_download_path = os.path.join(download_directory, folder_name_cleaned)
                
                with open(full_download_path, "wb") as f:
                    f.write(response.content)
            else:
                pass
    else:
        pass

In [86]:
import zipfile
import os


zip_directory = r"C:\Users\48516\Desktop\inzynierka\aktualne\klimat"


for filename in os.listdir(zip_directory):
    if filename.endswith(".zip"):
        zip_file_path = os.path.join(zip_directory, filename)

        with zipfile.ZipFile(zip_file_path, "r") as zip_ref:
            zip_ref.extractall(zip_directory)

        print(f"Wyodrębniono: {filename}")

Wyodrębniono: 2014_01_k.zip
Wyodrębniono: 2014_02_k.zip
Wyodrębniono: 2014_03_k.zip
Wyodrębniono: 2014_04_k.zip
Wyodrębniono: 2014_05_k.zip
Wyodrębniono: 2014_06_k.zip
Wyodrębniono: 2014_07_k.zip
Wyodrębniono: 2014_08_k.zip
Wyodrębniono: 2014_09_k.zip
Wyodrębniono: 2014_10_k.zip
Wyodrębniono: 2014_11_k.zip
Wyodrębniono: 2014_12_k.zip
Wyodrębniono: 2015_01_k.zip
Wyodrębniono: 2015_02_k.zip
Wyodrębniono: 2015_03_k.zip
Wyodrębniono: 2015_04_k.zip
Wyodrębniono: 2015_05_k.zip
Wyodrębniono: 2015_06_k.zip
Wyodrębniono: 2015_07_k.zip
Wyodrębniono: 2015_08_k.zip
Wyodrębniono: 2015_09_k.zip
Wyodrębniono: 2015_10_k.zip
Wyodrębniono: 2015_11_k.zip
Wyodrębniono: 2015_12_k.zip
Wyodrębniono: 2016_01_k.zip
Wyodrębniono: 2016_02_k.zip
Wyodrębniono: 2016_03_k.zip
Wyodrębniono: 2016_04_k.zip
Wyodrębniono: 2016_05_k.zip
Wyodrębniono: 2016_06_k.zip
Wyodrębniono: 2016_07_k.zip
Wyodrębniono: 2016_08_k.zip
Wyodrębniono: 2016_09_k.zip
Wyodrębniono: 2016_10_k.zip
Wyodrębniono: 2016_11_k.zip
Wyodrębniono: 2016_12_k.zip
Wyodrębniono: 2017_01_k.zip
Wyodrębniono: 2017_02_k.zip
Wyodrębniono: 2017_03_k.zip
Wyodrębniono: 2017_04_k.zip
Wyodrębniono: 2017_05_k.zip
Wyodrębniono: 2017_06_k.zip
Wyodrębniono: 2017_07_k.zip
Wyodrębniono: 2017_08_k.zip
Wyodrębniono: 2017_09_k.zip
Wyodrębniono: 2017_10_k.zip
Wyodrębniono: 2017_11_k.zip
Wyodrębniono: 2017_12_k.zip
Wyodrębniono: 2018_01_k.zip
Wyodrębniono: 2018_02_k.zip
Wyodrębniono: 2018_03_k.zip
Wyodrębniono: 2018_04_k.zip
Wyodrębniono: 2018_05_k.zip
Wyodrębniono: 2018_06_k.zip
Wyodrębniono: 2018_07_k.zip
Wyodrębniono: 2018_08_k.zip
Wyodrębniono: 2018_09_k.zip
Wyodrębniono: 2018_10_k.zip
Wyodrębniono: 2018_11_k.zip
Wyodrębniono: 2018_12_k.zip
Wyodrębniono: 2019_01_k.zip
Wyodrębniono: 2019_02_k.zip
Wyodrębniono: 2019_03_k.zip
Wyodrębniono: 2019_04_k.zip
Wyodrębniono: 2019_05_k.zip
Wyodrębniono: 2019_06_k.zip
Wyodrębniono: 2019_07_k.zip
Wyodrębniono: 2019_08_k.zip
Wyodrębniono: 2019_09_k.zip
Wyodrębniono: 2019_10_k.zip
Wyodrębniono: 2019_11_k.zip
Wyodrębniono: 2019_12_k.zip
Wyodrębniono: 2020_01_k.zip
Wyodrębniono: 2020_02_k.zip
Wyodrębniono: 2020_03_k.zip
Wyodrębniono: 2020_04_k.zip
Wyodrębniono: 2020_05_k.zip
Wyodrębniono: 2020_06_k.zip
Wyodrębniono: 2020_07_k.zip
Wyodrębniono: 2020_08_k.zip
Wyodrębniono: 2020_09_k.zip
Wyodrębniono: 2020_10_k.zip
Wyodrębniono: 2020_11_k.zip
Wyodrębniono: 2020_12_k.zip
Wyodrębniono: 2021_01_k.zip
Wyodrębniono: 2021_02_k.zip
Wyodrębniono: 2021_03_k.zip
Wyodrębniono: 2021_04_k.zip
Wyodrębniono: 2021_05_k.zip
Wyodrębniono: 2021_06_k.zip
Wyodrębniono: 2021_07_k.zip
Wyodrębniono: 2021_08_k.zip
Wyodrębniono: 2021_09_k.zip
Wyodrębniono: 2021_10_k.zip
Wyodrębniono: 2021_11_k.zip
Wyodrębniono: 2021_12_k.zip
Wyodrębniono: 2022_01_k.zip
Wyodrębniono: 2022_02_k.zip
Wyodrębniono: 2022_03_k.zip
Wyodrębniono: 2022_04_k.zip
Wyodrębniono: 2022_05_k.zip
Wyodrębniono: 2022_06_k.zip
Wyodrębniono: 2022_07_k.zip
Wyodrębniono: 2022_08_k.zip
Wyodrębniono: 2022_09_k.zip
Wyodrębniono: 2022_10_k.zip
Wyodrębniono: 2022_11_k.zip
Wyodrębniono: 2022_12_k.zip
Wyodrębniono: 2023_01_k.zip
Wyodrębniono: 2023_02_k.zip
Wyodrębniono: 2023_03_k.zip
Wyodrębniono: 2023_04_k.zip
Wyodrębniono: 2023_05_k.zip
Wyodrębniono: 2023_06_k.zip
Wyodrębniono: 2023_07_k.zip
Wyodrębniono: 2023_08_k.zip

In [4]:
import re
import pandas as pd
import os

csv_directory = r"C:\Users\48516\Desktop\inzynierka\aktualne\klimat"
dataframes = []

file_pattern = r"k_d_\d{2}_\d{4}\.csv"

for filename in os.listdir(csv_directory):
    if filename.endswith(".csv") and re.match(file_pattern, filename):
        csv_file_path = os.path.join(csv_directory, filename)
        encoding = 'ISO-8859-1'
        df = pd.read_csv(csv_file_path, encoding=encoding,header=None)
        dataframes.append(df)

combined_dataframe = pd.concat(dataframes, ignore_index=True)

new_column_names = {column: f"{i}" for i, column in enumerate(combined_dataframe.columns, 1)}
combined_dataframe = combined_dataframe.rename(columns=new_column_names)

filtered_dataframe = combined_dataframe[combined_dataframe.iloc[:, 1] == "KRAKÓW-OBSERWATORIUM"]

filtered_dataframe

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
2170,250190390,KRAKÓW-OBSERWATORIUM,2014,1,1,1.6,NaN,-1.1,NaN,0.3,NaN,-1.6,NaN,0.0,9.0,NaN,0,9.0
2171,250190390,KRAKÓW-OBSERWATORIUM,2014,1,2,3.2,NaN,-5.3,NaN,-1.5,NaN,-7.0,NaN,0.0,9.0,NaN,0,9.0
2172,250190390,KRAKÓW-OBSERWATORIUM,2014,1,3,8.0,NaN,-1.5,NaN,2.0,NaN,-4.5,NaN,0.0,9.0,NaN,0,9.0
2173,250190390,KRAKÓW-OBSERWATORIUM,2014,1,4,7.4,NaN,-1.7,NaN,2.7,NaN,-4.6,NaN,1.7,NaN,W,0,9.0
2174,250190390,KRAKÓW-OBSERWATORIUM,2014,1,5,9.5,NaN,4.4,NaN,7.0,NaN,1.0,NaN,0.9,NaN,W,0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270979,250190390,KRAKÓW-OBSERWATORIUM,2022,12,27,9.4,NaN,3.4,NaN,5.8,NaN,0.3,NaN,0.0,NaN,W,0,9.0
270980,250190390,KRAKÓW-OBSERWATORIUM,2022,12,28,7.3,NaN,-1.4,NaN,2.0,NaN,-5.7,NaN,0.0,9.0,NaN,0,9.0
270981,250190390,KRAKÓW-OBSERWATORIUM,2022,12,29,11.9,NaN,0.2,NaN,4.8,NaN,-5.0,NaN,0.0,NaN,W,0,9.0
270982,250190390,KRAKÓW-OBSERWATORIUM,2022,12,30,8.3,NaN,2.1,NaN,3.9,NaN,-3.7,NaN,0.0,NaN,W,0,9.0
270983,250190390,KRAKÓW-OBSERWATORIUM,2022,12,31,13.5,NaN,-0.6,NaN,5.6,NaN,-5.0,NaN,0.0,9.0,NaN,0,9.0

In [5]:

all_data1 = filtered_dataframe.iloc[:, [1, 2, 3, 4, 9, 13]]

all_data1 = all_data1.copy()
column_indices = all_data1.columns

new_column_names = {
    column_indices[0]: "stacja",
    column_indices[1]: "rok",
    column_indices[2]: "miesiąc",
    column_indices[3]: "dzień",
    column_indices[4]: "temperatura",
    column_indices[5]: "suma opadów"
}

all_data1.rename(columns=new_column_names, inplace=True)


all_data1 = all_data1.sort_values(by=[all_data1.columns[1],all_data1.columns[2],all_data1.columns[3]])
all_data1 = all_data1.reset_index(drop=True)
all_data1

                    stacja   rok  miesiąc  dzień  temperatura  suma opadów
0     KRAKÓW-OBSERWATORIUM  2014        1      1          0.3          0.0
1     KRAKÓW-OBSERWATORIUM  2014        1      2         -1.5          0.0
2     KRAKÓW-OBSERWATORIUM  2014        1      3          2.0          0.0
3     KRAKÓW-OBSERWATORIUM  2014        1      4          2.7          1.7
4     KRAKÓW-OBSERWATORIUM  2014        1      5          7.0          0.9
...                    ...   ...      ...    ...          ...          ...
3525  KRAKÓW-OBSERWATORIUM  2023        8     27         22.2          0.5
3526  KRAKÓW-OBSERWATORIUM  2023        8     28         19.7          0.1
3527  KRAKÓW-OBSERWATORIUM  2023        8     29         21.0          0.9
3528  KRAKÓW-OBSERWATORIUM  2023        8     30         18.5          0.3
3529  KRAKÓW-OBSERWATORIUM  2023        8     31         17.4          0.1

[3530 rows x 6 columns]

In [6]:
import pandas as pd
import os

csv_directory = r"C:\Users\48516\Desktop\inzynierka\aktualne\klimat"
dataframes = []

file_pattern = r"k_d_t_\d{2}_\d{4}\.csv"

for filename in os.listdir(csv_directory):
    if filename.endswith(".csv") and re.match(file_pattern, filename):
        csv_file_path = os.path.join(csv_directory, filename)
        encoding = 'ISO-8859-1'
        df = pd.read_csv(csv_file_path, encoding=encoding,header=None)
        dataframes.append(df)

combined_dataframe = pd.concat(dataframes, ignore_index=True)

new_column_names = {column: f"{i}" for i, column in enumerate(combined_dataframe.columns, 1)}
combined_dataframe = combined_dataframe.rename(columns=new_column_names)

filtered_dataframe = combined_dataframe[combined_dataframe.iloc[:, 1] == "KRAKÓW-OBSERWATORIUM"]

filtered_dataframe

,1,2,3,4,5,6,7,8,9,10,11,12,13
2170,250190390,KRAKÓW-OBSERWATORIUM,2014,1,1,0.3,NaN,94.5,NaN,0.7,NaN,7.3,NaN
2171,250190390,KRAKÓW-OBSERWATORIUM,2014,1,2,-1.5,NaN,89.5,NaN,1.0,NaN,4.3,NaN
2172,250190390,KRAKÓW-OBSERWATORIUM,2014,1,3,2.0,NaN,88.5,NaN,0.3,NaN,1.7,NaN
2173,250190390,KRAKÓW-OBSERWATORIUM,2014,1,4,2.7,NaN,88.5,NaN,0.3,NaN,6.0,NaN
2174,250190390,KRAKÓW-OBSERWATORIUM,2014,1,5,7.0,NaN,87.8,NaN,0.7,NaN,7.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270978,250190390,KRAKÓW-OBSERWATORIUM,2022,12,27,5.8,NaN,73.8,NaN,3.3,NaN,6.7,NaN
270979,250190390,KRAKÓW-OBSERWATORIUM,2022,12,28,2.0,NaN,78.0,NaN,0.3,NaN,3.3,NaN
270980,250190390,KRAKÓW-OBSERWATORIUM,2022,12,29,4.8,NaN,63.5,NaN,0.7,NaN,5.7,NaN
270981,250190390,KRAKÓW-OBSERWATORIUM,2022,12,30,3.9,NaN,83.5,NaN,0.7,NaN,4.7,NaN
270982,250190390,KRAKÓW-OBSERWATORIUM,2022,12,31,5.6,NaN,87.0,NaN,1.3,NaN,5.7,NaN

In [7]:

all_data2 = filtered_dataframe.iloc[:, [1, 2, 3,4, 7, 9, 11]]

all_data2 = all_data2.copy()
column_indices = all_data2.columns

new_column_names = {
    column_indices[0]: "stacja",
    column_indices[1]: "rok",
    column_indices[2]: "miesiąc",
    column_indices[3]: "dzień",
    column_indices[4]: "wilgotność",
    column_indices[5]: "prędkość wiatru",
    column_indices[6]: "zachmurzenine"
    
}

all_data2.rename(columns=new_column_names, inplace=True)


all_data2 = all_data2.sort_values(by=[all_data2.columns[1],all_data2.columns[2],all_data2.columns[3]])
all_data2 = all_data2.reset_index(drop=True)
all_data2

,stacja,rok,miesiąc,dzień,wilgotność,prędkość wiatru,zachmurzenine
0,KRAKÓW-OBSERWATORIUM,2014,1,1,94.5,0.7,7.3
1,KRAKÓW-OBSERWATORIUM,2014,1,2,89.5,1.0,4.3
2,KRAKÓW-OBSERWATORIUM,2014,1,3,88.5,0.3,1.7
3,KRAKÓW-OBSERWATORIUM,2014,1,4,88.5,0.3,6.0
4,KRAKÓW-OBSERWATORIUM,2014,1,5,87.8,0.7,7.0
...,...,...,...,...,...,...,...
3525,KRAKÓW-OBSERWATORIUM,2023,8,27,85.3,0.7,3.7
3526,KRAKÓW-OBSERWATORIUM,2023,8,28,89.5,1.7,8.0
3527,KRAKÓW-OBSERWATORIUM,2023,8,29,89.0,1.0,7.7
3528,KRAKÓW-OBSERWATORIUM,2023,8,30,89.5,1.3,7.7
3529,KRAKÓW-OBSERWATORIUM,2023,8,31,82.5,1.7,4.7

In [8]:
all_data = pd.concat([all_data1, all_data2.iloc[:, -3:]], axis=1)
all_data

,stacja,rok,miesiąc,dzień,temperatura,suma opadów,wilgotność,prędkość wiatru,zachmurzenine
0,KRAKÓW-OBSERWATORIUM,2014,1,1,0.3,0.0,94.5,0.7,7.3
1,KRAKÓW-OBSERWATORIUM,2014,1,2,-1.5,0.0,89.5,1.0,4.3
2,KRAKÓW-OBSERWATORIUM,2014,1,3,2.0,0.0,88.5,0.3,1.7
3,KRAKÓW-OBSERWATORIUM,2014,1,4,2.7,1.7,88.5,0.3,6.0
4,KRAKÓW-OBSERWATORIUM,2014,1,5,7.0,0.9,87.8,0.7,7.0
...,...,...,...,...,...,...,...,...,...
3525,KRAKÓW-OBSERWATORIUM,2023,8,27,22.2,0.5,85.3,0.7,3.7
3526,KRAKÓW-OBSERWATORIUM,2023,8,28,19.7,0.1,89.5,1.7,8.0
3527,KRAKÓW-OBSERWATORIUM,2023,8,29,21.0,0.9,89.0,1.0,7.7
3528,KRAKÓW-OBSERWATORIUM,2023,8,30,18.5,0.3,89.5,1.3,7.7
3529,KRAKÓW-OBSERWATORIUM,2023,8,31,17.4,0.1,82.5,1.7,4.7

In [9]:
all_data.to_csv("all_data.csv")